User.destroy_all
Category.destroy_all
Brand.destroy_all
Product.destroy_all
Request.destroy_all

# u1 = User.create(first_name: string, last_name: string, username: string, email: string, password: string, password_confirmation: string, profile_pic: string, user_type: string)

c1 = Category.create!(name: "Mancare", image: '/images/1')
c2 = Category.create!(name: "Backpacks", image: '/images/2')
c3 = Category.create!(name: "Trainers", image: '/images/3')
c4 = Category.create!(name: "Hoddies", image: '/images/4')
c5 = Category.create!(name: "Game C's", image: '/images/5')
c6 = Category.create!(name: "Watches", image: '/images/6')


b1 = Brand.create!(name: "Nivea", code: '1', image: '/images/7', logo: '/images/8.jpg')
b1 = Brand.create!(name: "Loreal", code: '2', image: '/images/9', logo: '/images/10')
b1 = Brand.create!(name: "Lynx", code: '3', image: '/images/11', logo: '/images/12')
b1 = Brand.create!(name: "MCM", code: '4', image: '/images/13', logo: '/images/14')
b1 = Brand.create!(name: "Louis Vuitton", code: '/images/5', image: '/images/15', logo: '/images/16')
b1 = Brand.create!(name: 'Hershel', code: '6', image: '/images/17', logo: '/images/18')
b1 = Brand.create!(name: 'Addidas', code: '7', image: '/images/19', logo: '/images/20')
b1 = Brand.create!(name: 'Nike', code: '8', image: '/images/21', logo: '/images/22')
b1 = Brand.create!(name: 'Reebok', code: '9', image: '/images/23', logo: '/images/24')
b1 = Brand.create!(name: 'Billionaires Boys Club', code: '/images/10', image: '/images/25', logo: '/images/26')
b1 = Brand.create!(name: 'Jack&Jones', code: '11', image: '/images/27', logo: '/images/28')
b1 = Brand.create!(name: 'Money', code: '12', image: '/images/29', logo: '/images/30')
b1 = Brand.create!(name: 'Playstation', code: '13', image: '/images/31', logo: '/images/32')
b1 = Brand.create!(name: 'Xbox', code: '14', image: '/images/33', logo: '/images/34')
b1 = Brand.create!(name: 'Nintendo', code: '15', image: '/images/35', logo: '/images/36')
b1 = Brand.create!(name: 'Apple', code: '16', image: '/images/37', logo: '/images/38')
b1 = Brand.create!(name: 'U-Boat', code: '17', image: '/images/39', logo: '/images/40')
b1 = Brand.create!(name: 'Marc Jacobs', code: '18', image: '/images/41', logo: '/images/42')

# b1.categories << c1

p1 = u1.products.create!(code: "1", name: "", image: "", price: "", description: "", category_id: integer, brand_id: integer, user_id: integer)
p2 = u1.products.create!(code: "2", name: "", image: "", price: "", description: "", category_id: integer, brand_id: integer, user_id: integer)
p3 = u1.products.create!(code: "3", name: "", image: "", price: "", description: "", category_id: integer, brand_id: integer, user_id: integer)
p4 = u1.products.create!(code: "4", name: "", image: "", price: "", description: "", category_id: integer, brand_id: integer, user_id: integer)
p5 = u1.products.create!(code: "5", name: "", image: "", price: "", description: "", category_id: integer, brand_id: integer, user_id: integer)
p6 = u1.products.create!(code: "6", name: "", image: "", price: "", description: "", category_id: integer, brand_id: integer, user_id: integer)
p7 = u1.products.create!(code: "7", name: "", image: "", price: "", description: "", category_id: integer, brand_id: integer, user_id: integer)
p8 = u1.products.create!(code: "8", name: "", image: "", price: "", description: "", category_id: integer, brand_id: integer, user_id: integer)
p9 = u1.products.create!(code: "9", name: "", image: "", price: "", description: "", category_id: integer, brand_id: integer, user_id: integer)
p10 = u1.products.create!(code: "10", name: "", image: "", price: "", description: "", category_id: integer, brand_id: integer, user_id: integer)
p11 = u1.products.create!(code: "11", name: "", image: "", price: "", description: "", category_id: integer, brand_id: integer, user_id: integer)
p12 = u1.products.create!(code: "12", name: "", image: "", price: "", description: "", category_id: integer, brand_id: integer, user_id: integer)
p13 = u1.products.create!(code: "13", name: "", image: "", price: "", description: "", category_id: integer, brand_id: integer, user_id: integer)
p14 = u1.products.create!(code: "14", name: "", image: "", price: "", description: "", category_id: integer, brand_id: integer, user_id: integer)
p15 = u1.products.create!(code: "15", name: "", image: "", price: "", description: "", category_id: integer, brand_id: integer, user_id: integer)
p16 = u1.products.create!(code: "16", name: "", image: "", price: "", description: "", category_id: integer, brand_id: integer, user_id: integer)
p17 = u1.products.create!(code: "17", name: "", image: "", price: "", description: "", category_id: integer, brand_id: integer, user_id: integer)
p18 = u1.products.create!(code: "18", name: "", image: "", price: "", description: "", category_id: integer, brand_id: integer, user_id: integer)
p19 = u1.products.create!(code: "19", name: "", image: "", price: "", description: "", category_id: integer, brand_id: integer, user_id: integer)
p20 = u1.products.create!(code: "20", name: "", image: "", price: "", description: "", category_id: integer, brand_id: integer, user_id: integer)
p21 = u1.products.create!(code: "21", name: "", image: "", price: "", description: "", category_id: integer, brand_id: integer, user_id: integer)
p22 = u1.products.create!(code: "22", name: "", image: "", price: "", description: "", category_id: integer, brand_id: integer, user_id: integer)
p23 = u1.products.create!(code: "23", name: "", image: "", price: "", description: "", category_id: integer, brand_id: integer, user_id: integer)
p24 = u1.products.create!(code: "24", name: "", image: "", price: "", description: "", category_id: integer, brand_id: integer, user_id: integer)
p25 = u1.products.create!(code: "25", name: "", image: "", price: "", description: "", category_id: integer, brand_id: integer, user_id: integer)
p26 = u1.products.create!(code: "26", name: "", image: "", price: "", description: "", category_id: integer, brand_id: integer, user_id: integer)
p27 = u1.products.create!(code: "27", name: "", image: "", price: "", description: "", category_id: integer, brand_id: integer, user_id: integer)
p28 = u1.products.create!(code: "28", name: "", image: "", price: "", description: "", category_id: integer, brand_id: integer, user_id: integer)
p29 = u1.products.create!(code: "29", name: "", image: "", price: "", description: "", category_id: integer, brand_id: integer, user_id: integer)
p30 = u1.products.create!(code: "30", name: "", image: "", price: "", description: "", category_id: integer, brand_id: integer, user_id: integer)
p31 = u1.products.create!(code: "31", name: "", image: "", price: "", description: "", category_id: integer, brand_id: integer, user_id: integer)
p32 = u1.products.create!(code: "32", name: "", image: "", price: "", description: "", category_id: integer, brand_id: integer, user_id: integer)
p33 = u1.products.create!(code: "33", name: "", image: "", price: "", description: "", category_id: integer, brand_id: integer, user_id: integer)
p34 = u1.products.create!(code: "34", name: "", image: "", price: "", description: "", category_id: integer, brand_id: integer, user_id: integer)
p35 = u1.products.create!(code: "35", name: "", image: "", price: "", description: "", category_id: integer, brand_id: integer, user_id: integer)
p36 = u1.products.create!(code: "36", name: "", image: "", price: "", description: "", category_id: integer, brand_id: integer, user_id: integer)
p37 = u1.products.create!(code: "37", name: "", image: "", price: "", description: "", category_id: integer, brand_id: integer, user_id: integer)
p38 = u1.products.create!(code: "38", name: "", image: "", price: "", description: "", category_id: integer, brand_id: integer, user_id: integer)
p39 = u1.products.create!(code: "39", name: "", image: "", price: "", description: "", category_id: integer, brand_id: integer, user_id: integer)
p40 = u1.products.create!(code: "40", name: "", image: "", price: "", description: "", category_id: integer, brand_id: integer, user_id: integer)
p41 = u1.products.create!(code: "41", name: "", image: "", price: "", description: "", category_id: integer, brand_id: integer, user_id: integer)
p42 = u1.products.create!(code: "42", name: "", image: "", price: "", description: "", category_id: integer, brand_id: integer, user_id: integer)
p43 = u1.products.create!(code: "43", name: "", image: "", price: "", description: "", category_id: integer, brand_id: integer, user_id: integer)
p44 = u1.products.create!(code: "44", name: "", image: "", price: "", description: "", category_id: integer, brand_id: integer, user_id: integer)
p45 = u1.products.create!(code: "45", name: "", image: "", price: "", description: "", category_id: integer, brand_id: integer, user_id: integer)
p46 = u1.products.create!(code: "46", name: "", image: "", price: "", description: "", category_id: integer, brand_id: integer, user_id: integer)
p47 = u1.products.create!(code: "47", name: "", image: "", price: "", description: "", category_id: integer, brand_id: integer, user_id: integer)
p48 = u1.products.create!(code: "48", name: "", image: "", price: "", description: "", category_id: integer, brand_id: integer, user_id: integer)
p49 = u1.products.create!(code: "49", name: "", image: "", price: "", description: "", category_id: integer, brand_id: integer, user_id: integer)
p50 = u1.products.create!(code: "50", name: "", image: "", price: "", description: "", category_id: integer, brand_id: integer, user_id: integer)
p51 = u1.products.create!(code: "51", name: "", image: "", price: "", description: "", category_id: integer, brand_id: integer, user_id: integer)
p52 = u1.products.create!(code: "52", name: "", image: "", price: "", description: "", category_id: integer, brand_id: integer, user_id: integer)
p53 = u1.products.create!(code: "53", name: "", image: "", price: "", description: "", category_id: integer, brand_id: integer, user_id: integer)
p54 = u1.products.create!(code: "54", name: "", image: "", price: "", description: "", category_id: integer, brand_id: integer, user_id: integer)
p55 = u1.products.create!(code: "55", name: "", image: "", price: "", description: "", category_id: integer, brand_id: integer, user_id: integer)
p56 = u1.products.create!(code: "56", name: "", image: "", price: "", description: "", category_id: integer, brand_id: integer, user_id: integer)
p38 = u1.products.create!(code: "38", name: "", image: "", price: "", description: "", category_id: integer, brand_id: integer, user_id: integer)
p39 = u1.products.create!(code: "39", name: "", image: "", price: "", description: "", category_id: integer, brand_id: integer, user_id: integer)
p40 = u1.products.create!(code: "40", name: "", image: "", price: "", description: "", category_id: integer, brand_id: integer, user_id: integer)
p41 = u1.products.create!(code: "41", name: "", image: "", price: "", description: "", category_id: integer, brand_id: integer, user_id: integer)
p42 = u1.products.create!(code: "42", name: "", image: "", price: "", description: "", category_id: integer, brand_id: integer, user_id: integer)
p43 = u1.products.create!(code: "43", name: "", image: "", price: "", description: "", category_id: integer, brand_id: integer, user_id: integer)
p44 = u1.products.create!(code: "44", name: "", image: "", price: "", description: "", category_id: integer, brand_id: integer, user_id: integer)
p45 = u1.products.create!(code: "45", name: "", image: "", price: "", description: "", category_id: integer, brand_id: integer, user_id: integer)
p46 = u1.products.create!(code: "46", name: "", image: "", price: "", description: "", category_id: integer, brand_id: integer, user_id: integer)
p47 = u1.products.create!(code: "47", name: "", image: "", price: "", description: "", category_id: integer, brand_id: integer, user_id: integer)
p48 = u1.products.create!(code: "48", name: "", image: "", price: "", description: "", category_id: integer, brand_id: integer, user_id: integer)





# LEAVE REQUESTS
